#!/bin/bash

# Default location and name for saveset.

IDL_SAVESET_BASE=./
IDL_SAVESET_DEFAULT=miri_ql.sav

IDL_SAVESET=$IDL_SAVESET_BASE$IDL_SAVESET_DEFAULT

# Run the virtual machine, assumed .sav file. 
idl -vm=$IDL_SAVESET

